import type { Metadata } from "next";
import { Outfit, Geist_Mono } from "next/font/google"; // Import the Outfit font
import "./globals.css";
import Navbar from "@/components/Navbar";

const outfit = Outfit({
  variable: "--font-outfit", // Declare the CSS variable for Outfit
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "PlanPal",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${outfit.variable} ${geistMono.variable} antialiased m-6 mb-[100px] lg:mx-[500px]`} // Use the Outfit font here
      >
      <Navbar />
        {children}
      </body>
    </html>
  );
}